version: "3.8"

services:
  node:
    container_name: nodejs
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    volumes:
      - ./nodejs:/workspace
      - node_modules_volume:/workspace/node_modules:delegated
    tty: true
    ports:
      - 4000:4000

volumes:
  node_modules_volume:
