version: "3.8"

services:
  node:
    container_name: nodejs
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    volumes:
      - ./nodejs:/workspace
      - node_modules_volume:/workspace/node_modules:delegated
      - ./nodejs/.firebaserc:/opt/firebase/.firebaserc
      - ./nodejs/firebase.json:/opt/firebase/firebase.json
    tty: true
    ports:
      - 9099:9099 # Firebase Authentication
      - 5001:5001 # Clound Functions
      - 8080:8080 # Cloud Firestore
      - 9000:9000 # Realtime Database
      - 5050:5050 # Firebase Hosting
      - 8085:8085 # Cloud Pub/Sub
      - 9199:9199 # Cloud Storage
      - 4000:4000 # Emulator Suite UI
    networks:
      - default

volumes:
  node_modules_volume:
